name: Update PS Trophies JSON

on:
  push:
    branches: [ master ]

jobs:
  update_json:
    defaults:
      run:
        working-directory: ./scripts
    env:
      NPSSO: ${{ secrets.PSN_NPSSO }}
    runs-on: ubuntu-latest
    name: Update JSON resources
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies without changing lockfile
        run: yarn install --frozen-lockfile
      - name: Run tsc compiler job
        uses: icrawl/action-tsc@v1
      - run: ls
      - run: pwd
      - run: tsc
      - name: Update JSON file
        uses: test-room-7/action-update-file@v1.4.0
        with:
          file-path: _data/psn/games.json
          commit-msg: Update JSON for PSN Trophies
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-removing: true
